### ISSUE TITLE
More understandable names?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/commonsmisc#1]
I believe these names would convey the meaning better:

errorcode -> errorCode
imageseditedelse -> imagesEditedBySomeoneElse
imagesfeatured -> featuredImages
imagesused -> uniqueUsedImages
imagesnumofusings -> articlesUsingImages
thanksreceived -> thanksReceived

Cheers!

**Comment by urbanecm** [comment]
Ok, thanks for the better names! I had no idea about how to name them, so I figured out something and was hoping somebody else will have better ideas. 

Changed.
