### ISSUE TITLE
API to show the number of Wikidata edits made through the Commons app

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/commonsmisc#12]
To implement https://github.com/commons-app/apps-android-commons/issues/2430 we need an API to show the number of Wikidata edits made through the Commons app.

Going forward, another task might need a modified version of the API + an additional API for the following task:
https://github.com/commons-app/apps-android-commons/issues/2428

- to show leaderboard for Wikidata edits in a given time frame
- to show a particular user's edits in a given time frame (as the user might not be part of the leaderboard).

I am familiar with the query and am willing to take this up.

**Comment by maskaravivek** [comment]
Am planning to use the following query: 

https://quarry.wmflabs.org/query/33319

**Comment by urbanecm** [comment]
I think we can call this resolved. https://tools.wmflabs.org/urbanecmbot/commonsmisc/wikidataedits.py?user=Maskaravivek

**Comment by VojtechDostal** [comment]
@urbanecm Does it allow specific timeframes?

**Comment by urbanecm** [comment]
It doesn't look so, however, that should be pretty simple to add. If we want that, please open either a new issue or a pull request.
