### ISSUE TITLE
Getting 500 error while calling API

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/commonsmisc#13]
Both the upload count and feedback API doesn't seem to be working. 

https://tools.wmflabs.org/urbanecmbot/commonsmisc/uploadsbyuser.py?user=Maskaravivek

@urbanecm Can you check if the tool is up and running.

**Comment by nicolas-raoul** [comment]
Even the example requests at the end of the README file trigger error 500 :'-/

**Comment by urbanecm** [comment]
Fixed.

**Comment by maskaravivek** [comment]
Did something break again? This API isn't returning a response: 

https://tools.wmflabs.org/urbanecmbot/commonsmisc/feedback.py?user=Maskaravivek

**Comment by urbanecm** [comment]
Yes, I played with it for some minutes :(. Will stop testing on prod :D.

**Comment by maskaravivek** [comment]
okay. :D
