### ISSUE TITLE
API for Beta Commons

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/commonsmisc#16]
It would be great to have APIs corresponding to the beta commons server that can be consumed by the commons app as discussed in https://github.com/commons-app/apps-android-commons/issues/2975

**Comment by urbanecm** [comment]
Resolved with 0f5f5dd7af6037102b39e9ce67e251b410b14292 and f6eb89367e136b4c7bb556851eca3ce96fc15612. You can now submit https://tools.wmflabs.org/urbanecmbot/commonsmisc/feedback.py?user=Martin_Urbanec&fetch=deletedUploads&db=testcommonswiki or https://tools.wmflabs.org/urbanecmbot/commonsmisc/test.py?user=Jagro&db=testcommonswiki and query other database. Theoretically, you can use even non-commons databases, like "cswiki" or "enwiki". Database looks the same, so it will work.

**Comment by urbanecm** [comment]
Ahh, you didn't mean prod test (https://test-commons.wikimedia.org), but beta commons <https://commons.wikimedia.beta.wmflabs.org/wiki/Main_Page>... That'll be kinda harder, let me think off something.

**Comment by urbanecm** [comment]
Placed access request, I don't have access to beta commons database <https://phabricator.wikimedia.org/T224865>.

**Comment by maskaravivek** [comment]
I meant beta commons ie https://commons.wikimedia.beta.wmflabs.org

**Comment by urbanecm** [comment]
Resolved a few hours later. https://tools.wmflabs.org/urbanecmbot/commonsmisc/feedback.py?user=Martin_Urbanec&labs=commonswiki looks to give the requested data. Can you please test and let me know?

**Comment by urbanecm** [comment]
Updated docs in 5d10feef536830ddd620f00542a022fcbdca0fa6

**Comment by maskaravivek** [comment]
> Resolved a few hours later. https://tools.wmflabs.org/urbanecmbot/commonsmisc/feedback.py?user=Martin_Urbanec&labs=commonswiki looks to give the requested data. Can you please test and let me know?

this link is not working for me. 

<img width="729" alt="Screen Shot 2019-06-03 at 11 18 40 PM" src="https://user-images.githubusercontent.com/3069373/58822796-f0b13c00-8655-11e9-81e1-07ae884752d3.png">

**Comment by urbanecm** [comment]
That's an DNS issue at your end, try to refresh?

**Comment by maskaravivek** [comment]
Works now. Thanks a lot. :)

**Comment by urbanecm** [comment]
Does this also mean the API works as it is supposed to?

**Comment by maskaravivek** [comment]
Yes. Closing the issue as resolved. Thanks a lot for a quick resolution. :)
